name: zas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  provider: ^6.1.1
  card_swiper: ^3.0.1
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  date_time_picker: ^2.1.0
  image_picker: ^1.0.5
  flutter_paypal_payment: ^1.0.6
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logozas.jpeg"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/logozas.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logozas.jpeg"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/logozas.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/logozas.jpeg